export const characters = [
    {
    "content": [
        {
            "id": 1,
            "name": "Tanjiro Kamado",
            "age": 16,
            "gender": "Male",
            "race": "Human",
            "description": "Is the main protagonist of Demon Slayer. He joined the Demon Slayer Corp to find a remedy to turn his sister, Nezuko Kamado, back into a human and to hunt down and kill demons.",
            "img": "https://www.demonslayer-api.com/api/v1/characters/images/1.webp",
            "affiliation_id": 1,
            "arc_id": 1,
            "quote": "Work at it. All I can do is work hard! That´s the story of my life!"
        },
        {
            "id": 2,
            "name": "Nezuko Kamado",
            "age": 14,
            "gender": "Female",
            "race": "Demon",
            "description": "She is a demon and the younger sister of Tanjiro Kamado and one of the two remaining members of the Kamado family. Formerly a human, she was attacked and transformed into a demon by Muzan Kibutsuji.",
            "img": "https://www.demonslayer-api.com/api/v1/characters/images/2.webp",
            "affiliation_id": 1,
            "arc_id": 1,
            "quote": "Humans are to be protected and saved... I will never hurt them."
        },
        {
            "id": 3,
            "name": "Giyu Tomioka",
            "age": 21,
            "gender": "Male",
            "race": "Human",
            "description": "He is a Demon Slayer of the Demon Slayer Corps and the current Water Hashira. He has a reserved personality and a very strong sense of justice.",
            "img": "https://www.demonslayer-api.com/api/v1/characters/images/3.webp",
            "affiliation_id": 2,
            "arc_id": 1,
            "quote": "Feel the rage. The powerful, pure rage of not being able to forgive will become your unswerving drive to take action."
        },
        {
            "id": 4,
            "name": "Sakonji Urokodaki",
            "age": 70,
            "gender": "Male",
            "race": "Human",
            "description": "Sakonji Urokodaki is a retired member of the Demon Slayer Corps, having held the position of the previous Water Hashira. He is the main cultivator of the Water Breathing style, having trained Makomo, Sabito, Giyu Tomioka, and Tanjiro Kamado.",
            "img": "https://www.demonslayer-api.com/api/v1/characters/images/4.webp",
            "affiliation_id": 3,
            "arc_id": 1,
            "quote": "Remember to take a long breath so the oxygen flows into every cell in your body."
        },
        {
            "id": 5,
            "name": "Sabito",
            "age": 13,
            "gender": "Male",
            "race": "Human",
            "description": "Sabito was a former apprentice of Sakonji Urokodaki. He appeared to assist Tanjiro Kamado in his preparations for the Final Selection exam.",
            "img": "https://www.demonslayer-api.com/api/v1/characters/images/5.webp",
            "affiliation_id": 1,
            "arc_id": 1,
            "quote": "You have to make sure you never forget any of the secrets Urokodaki taught you! Pound it into the marrow of your bones!"
        },
        {
            "id": 6,
            "name": "Makomo",
            "age": 12,
            "gender": "Female",
            "race": "Human",
            "description": "Makomo and Sabito were both orphaned from their respective families and adopted by Sakonji, who trained them both and permitted them to attend the Demon Slayer Corps´Final Selection.",
            "img": "https://www.demonslayer-api.com/api/v1/characters/images/6.webp",
            "affiliation_id": 1,
            "arc_id": 1,
            "quote": "Train until it kills you. Because really, when you get down to it, there´s nothing else you can do."
        },
        {
            "id": 7,
            "name": "Hand Demon",
            "age": 47,
            "gender": "Male",
            "race": "Demon",
            "description": "The Hand Demon was the primary antagonist of the Final Selection Arc of Demon Slayer. He was a notorious demon who killed thirteen of Sakonji Urokodaki´s apprentices",
            "img": "https://www.demonslayer-api.com/api/v1/characters/images/7.webp",
            "affiliation_id": 6,
            "arc_id": 1,
            "quote": "I´ve been here so long... that dynasties have risen and fallen! Again and again! All while I´ve been trapped here! Unforgivable! Unforgivable!"
        },
        {
            "id": 8,
            "name": "Genya Shinazugawa",
            "age": 16,
            "gender": "Male",
            "race": "Human",
            "description": "He is the younger brother of the Wind Hashira and as one of the five that survived Final Selection, Genya possesses a relatively strong foundation as a Demon Slayer even without utilizing a Breathing Style.",
            "img": "https://www.demonslayer-api.com/api/v1/characters/images/8.webp",
            "affiliation_id": 1,
            "arc_id": 1,
            "quote": "I´ll do it. I´m gonna do it. I have to do it. Think only about winning. I will not let my brother, or my master, or any of my comrades die!"
        },
        {
            "id": 9,
            "name": "Zenitsu Agatsuma",
            "age": 16,
            "gender": "Male",
            "race": "Human",
            "description": "Zenitsu Agatsuma is one of the main characters of Demon Slayer and along with Inosuke Hashibira, a travelling companion of Tanjiro Kamado and Nezuko Kamado. He is also a Demon Slayer in the Demon Slayer Corps.",
            "img": "https://www.demonslayer-api.com/api/v1/characters/images/9.webp",
            "affiliation_id": 1,
            "arc_id": 1,
            "quote": "I hate myself more than anyone. I always think I have to get my act together, but I end up cowering, running away, sniveling. I want to change. I want to be a competent person."
        },
        {
            "id": 10,
            "name": "Inosuke Hashibira",
            "age": 15,
            "gender": "Male",
            "race": "Human",
            "description": "Inosuke is short-tempered, confrontational, abrasive and proud. He always likes to think he is the strongest fighter in a situation, constantly challenging most people he comes across and wanting others to respect and praise him for his skill.",
            "img": "https://www.demonslayer-api.com/api/v1/characters/images/10.webp",
            "affiliation_id": 1,
            "arc_id": 1,
            "quote": "Everything that dies returns to the earth, but crying won´t bring any of them back, so no matter how frusturated you feel, don´t cry!"
        },
        {
            "id": 11,
            "name": "Aoi Kanzaki",
            "age": 16,
            "gender": "Female",
            "race": "Human",
            "description": "Aoi Kanzaki is a Demon Slayer of the Demon Slayer Corps. However, she works as a helper at the Butterfly Mansion, rather than taking to the front lines and fighting demons.",
            "img": "https://www.demonslayer-api.com/api/v1/characters/images/11.webp",
            "affiliation_id": 1,
            "arc_id": 1,
            "quote": "Compared to you guys, I´m not so important, so thanks aren´t necessary. I survived selection due to pure luck. Since then I´ve been afraid to fight, so I´m a coward."
        },
        {
            "id": 12,
            "name": "Kanao Tsuyuri",
            "age": 16,
            "gender": "Female",
            "race": "Human",
            "description": "Kanao Tsuyuri is the adopted sister of Shinobu and Kanae Kocho.  She became unable to make decisions by herself and she has a coin to flip and decide which path to follow when she doesn´t know what to do.",
            "img": "https://www.demonslayer-api.com/api/v1/characters/images/12.webp",
            "affiliation_id": 1,
            "arc_id": 1,
            "quote": "Somehow I feel the people I care for and those important to me will still be alive tomorrow. But that´s just my hope and there´s no way I can promise that with any certainty."
        },
        {
            "id": 13,
            "name": "Swamp Demon",
            "age": null,
            "gender": "Male",
            "race": "Demon",
            "description": "He is the main antagonist of the Kidnapper´s Bog Arc. He was a demon who went through a rash of kidnappings during the first mission of Tanjiro Kamado for the Demon Slayer Corps.",
            "img": "https://www.demonslayer-api.com/api/v1/characters/images/13.webp",
            "affiliation_id": 6,
            "arc_id": 2,
            "quote": "Don´t interfere! You´ll ruin the girl´s freshness! She gets less and less tasty with each moment that passes!"
        },
        {
            "id": 14,
            "name": "Muzan Kibutsuji",
            "age": 10000,
            "gender": "Male",
            "race": "Demon",
            "description": "Muzan Kibutsuji is the main antagonist of Demon Slayer. He is the Demon King, the progenitor of all other demons in existence, and the leader of the Twelve Kizuki, an organization made up of the twelve strongest demons under his direct command.",
            "img": "https://www.demonslayer-api.com/api/v1/characters/images/14.webp",
            "affiliation_id": 4,
            "arc_id": 2,
            "quote": "The one thing I hate is \"change\". Changes in circumstances. Changes in body. Changes in emotion. In most cases, every change is \"degradation\". It is decline. The one thing I like is \"permanence\". If something doesn´t change for an eternity. It´s in a perfect state."
        },
        {
            "id": 15,
            "name": "Tamayo",
            "age": 500,
            "gender": "Female",
            "race": "Demon",
            "description": "Tamayo is a gentle, wise, and incredibly intelligent demon. Having devoted most of her life to the researching of demons and human transformation into one",
            "img": "https://www.demonslayer-api.com/api/v1/characters/images/15.webp",
            "affiliation_id": 1,
            "arc_id": 3,
            "quote": "I don´t need to be stronger than you to kill you. I can just make you weaker. Just as you´ll do whatever it takes to stay alive, I... No, we, will do whatever it takes to kill you"
        },
        {
            "id": 16,
            "name": "Yushiro",
            "age": 35,
            "gender": "Male",
            "race": "Demon",
            "description": "He only cares for Tamayo and hates when others get in the way of his spending time with her",
            "img": "https://www.demonslayer-api.com/api/v1/characters/images/16.webp",
            "affiliation_id": 1,
            "arc_id": 3,
            "quote": "Someone who never gives to others will someday become unable to receive anything from them."
        },
        {
            "id": 17,
            "name": "Susamaru",
            "age": null,
            "gender": "Female",
            "race": "Demon",
            "description": "Susamaru, also known as the Temari Demon, was one of the two primary antagonists in the Asakusa Arc of Demon Slayer along with Yahaba. She was a demon who was tricked into believing she was a member of the Twelve Demon Moons.",
            "img": "https://www.demonslayer-api.com/api/v1/characters/images/17.webp",
            "affiliation_id": 6,
            "arc_id": 3,
            "quote": "Let´s keep playing until dawn! Until your life ends"
        },
        {
            "id": 18,
            "name": "Yahaba",
            "age": null,
            "gender": "Male",
            "race": "Demon",
            "description": "Yahaba, also known as the Arrow Demon, was one of the two primary antagonists in the Asakusa Arc of Demon Slayer, along with Susamaru. He was a demon who was tricked into believing he was a member of the Twelve Demon Moons.",
            "img": "https://www.demonslayer-api.com/api/v1/characters/images/18.webp",
            "affiliation_id": 6,
            "arc_id": 3,
            "quote": "How will we kill them? Brutally of course!"
        },
        {
            "id": 19,
            "name": "Kyogai",
            "age": null,
            "gender": "Male",
            "race": "Demon",
            "description": "Kyogai was a demon formerly affiliated with the Twelve Demon Moons, having previously held the position of Lower Rank Six before Muzan Kibutsuji excommunicated him for reaching his limit as a demon and losing his ability to become stronger.",
            "img": "https://www.demonslayer-api.com/api/v1/characters/images/19.webp",
            "affiliation_id": 4,
            "arc_id": 4,
            "quote": "Demons... Exist for a purpose."
        },
        {
            "id": 20,
            "name": "Shinobu Kocho",
            "age": 18,
            "gender": "Female",
            "race": "Human",
            "description": "Shinobu is the current Insect Hashira. After a demon killed her parents, she joined the Demon Slayer Corps in order to protect others from suffering the same fate as her.",
            "img": "https://www.demonslayer-api.com/api/v1/characters/images/20.webp",
            "affiliation_id": 2,
            "arc_id": 5,
            "quote": "I once believed that the road of happiness continued forever and ever into the distance. When it was destroyed, I realized for the first time that it lies upon a thin sheet of glass."
        },
        {
            "id": 21,
            "name": "Murata",
            "age": 21,
            "gender": "Male",
            "race": "Human",
            "description": "Not much is known about Murata, however, he does not like it when a hunter of lower rank chastises him. He is somewhat timid, however he does seem braver than most.",
            "img": "https://www.demonslayer-api.com/api/v1/characters/images/21.webp",
            "affiliation_id": 1,
            "arc_id": 5,
            "quote": "Tomioka remembered my name... We were together since the Final Selection too...! I know there´s a huge difference between us but we were in the same batch, man...!"
        },
        {
            "id": 22,
            "name": "Spider Son",
            "age": null,
            "gender": "Male",
            "race": "Demon",
            "description": "He was member of the Spider Family, and he takes the form of a giant spider possessing a human head. His face, like Mother and Daughter, had the same facial features of red dots, white skin and hair similar to his \"younger brother\" Rui.",
            "img": "https://www.demonslayer-api.com/api/v1/characters/images/22.webp",
            "affiliation_id": 5,
            "arc_id": 5,
            "quote": "There´s nothing to be afraid of. When the poison runs throughout your system and you become a spider, your mind will be gone."
        },
        {
            "id": 23,
            "name": "Spider Daughter",
            "age": null,
            "gender": "Female",
            "race": "Demon",
            "description": "She was member of the Spider Family, and she is shown to be the most cautious within her \"family,\" having instead opted to observe and stand back rather than jump right into the battle against Demon Slayers.",
            "img": "https://www.demonslayer-api.com/api/v1/characters/images/23.webp",
            "affiliation_id": 5,
            "arc_id": 5,
            "quote": "I only ever worried about myself. They were dumb, but I was different. But now I´ve messed up!"
        },
        {
            "id": 24,
            "name": "Spider Mother",
            "age": null,
            "gender": "Female",
            "race": "Demon",
            "description": "She was member of the Spider Family. Like most demons, Mother was cruel, unfeeling, and murderous towards humans. She ruthlessly controlled dozens of Demon Slayers through her threads and manipulated them into killing each other.",
            "img": "https://www.demonslayer-api.com/api/v1/characters/images/24.webp",
            "affiliation_id": 5,
            "arc_id": 5,
            "quote": "Arrgh! Die! Die! Die now! If you don´t, I´ll suffer an awful fate!"
        },
        {
            "id": 25,
            "name": "Spider Father",
            "age": null,
            "gender": "Male",
            "race": "Demon",
            "description": "He was member of the Spider Family. Physically, he was the most formidable of his \"family\", possessing great height and a powerfully built physique.",
            "img": "https://www.demonslayer-api.com/api/v1/characters/images/25.webp",
            "affiliation_id": 5,
            "arc_id": 5,
            "quote": "Stay away... from... my... family!"
        }


    ]
}
];